{{- if .Values.operator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-operator
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.agent" . | indent 4 }}
{{ include "config.operator.annotations" . | indent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-operator
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreAgent" . | indent 4 }}
{{ include "config.operator.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-operator
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.agent" . | indent 8 }}
{{ include "config.operator.annotations" . | indent 8 }}
      labels:
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-operator
{{ include "config.labels.common" . | indent 8 }}
{{ include "config.labels.roles.coreAgent" . | indent 8 }}
{{ include "config.operator.labels" . | indent 8 }}
    spec:
{{ include "securityContext.pod" . | indent 6 }}
{{ include "config.operator.scheduling" . | indent 6 }}
{{ include "config.operator.sa" . | indent 6 }}
{{ include "config.operator.imagePullSecrets" . | indent 6}}
{{ include "config.operator.priorityClassName" . | indent 6}}
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{ .Chart.Name }}-operator
        image: "{{ .Values.operator.image }}:{{ .Values.operator.imageTag }}"
        imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
{{ include "securityContext.container" . | indent 8 }}
        command:
        - /manager
        envFrom:
{{ include "config.envFrom.agent" . | indent 8 }}
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.proxies" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.operator.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.operator.resources.limits | indent 12 }}
          {{- end }}
{{- end }}
