{{- $singleNamespace := include "config.singleNamespace" . | trim | lower | eq "true" -}}
{{- if and .Values.rbac.enabled (not $singleNamespace) (or .Values.agent.enabled (not .Values.organizationKey)) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "polyaxon.fullname" . }}-agent-sa
  namespace: {{ .Release.Namespace }}
{{ include "config.agent.serviceAccountAnnotations" . | indent 2 }}
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-agent-sa
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "polyaxon.fullname" . }}-agent-clusterrole
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-agent-clusterrole
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
rules:
{{- if .Values.agent.watchCluster }}
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["watch", "list", "patch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - nonResourceURLs:
    - /version/
    verbs: ["get"]
{{- end }}
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list", "create", "delete", "patch" ]
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "watch", "list", "create", "delete", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "secrets" ]
    verbs: [ "get", "update", "patch", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "create", "patch", "delete", "list" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "create", "patch", "delete", "list" ]
  - apiGroups: [ "metrics.k8s.io" ]
    resources: [ "pods", "nodes" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "events", "pods/status", "pods/log" ]
    verbs: [ "watch", "get", "list" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "get", "create" ]
  - apiGroups: [ "core.polyaxon.com" ]
    resources: [ "operations" ]
    verbs: [ "get", "watch", "list", "create", "delete", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "polyaxon.fullname" . }}-agent-clusterrole-binding
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-agent-clusterrole-binding
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreConfig" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "polyaxon.fullname" . }}-agent-clusterrole
subjects:
  - kind: ServiceAccount
    name: {{ template "polyaxon.fullname" . }}-agent-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
