{{- if .Values.beat.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-beat
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.platform" . | indent 4 }}
{{ include "config.beat.annotations" . | indent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-beat
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreWorker" . | indent 4 }}
{{ include "config.beat.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.beat.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-beat
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.platform" . | indent 8 }}
{{ include "config.beat.annotations" . | indent 8 }}
      labels:
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-beat
{{ include "config.labels.common" . | indent 8 }}
{{ include "config.labels.roles.coreWorker" . | indent 8 }}
{{ include "config.beat.labels" . | indent 8 }}
    spec:
{{ include "securityContext.pod" . | indent 6 }}
{{ include "config.beat.scheduling" . | indent 6 }}
{{ include "config.beat.imagePullSecrets" . | indent 6}}
{{ include "config.beat.priorityClassName" . | indent 6}}
      containers:
      - name: {{ .Chart.Name }}-beat
        image: "{{ .Values.beat.image }}:{{ .Values.beat.imageTag }}"
        imagePullPolicy: {{ .Values.beat.imagePullPolicy }}
{{ include "securityContext.container" . | indent 8 }}
        args: ["beat"]
        envFrom:
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.secret" . | indent 8 }}
{{ include "config.envFrom.platform" . | indent 8 }}
        env:
        - name: POLYAXON_IS_BEAT
          value: "true"
{{ include "config.envs" . | indent 8 }}
        livenessProbe:
          exec:
            command: ["/bin/bash", "./entrypoint.sh", "healthz"]
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 10
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command: ["/bin/bash", "./entrypoint.sh", "healthz"]
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 10
          timeoutSeconds: 10
        resources:
          requests:
{{ toYaml .Values.beat.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.beat.resources.limits | indent 12 }}
          {{- end }}
{{- end }}
