apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polyaxon.fullname" . }}-config
  labels:
    app: {{ template "polyaxon.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.config }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-beat
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.types.config }}
    app.kubernetes.io/managed-by: "helm"
data:
  # Cluster
  POLYAXON_CLUSTER_ID: {{ default "" .Values.clusterId | quote }}
  {{- if .Values.allowedHosts }}
  POLYAXON_ALLOWED_HOSTS: {{ toJson .Values.allowedHosts | quote }}
  {{- end }}
  {{- if .Values.apiHost }}
  POLYAXON_API_HOST: {{ .Values.apiHost | quote }}
  {{- end }}
  POLYAXON_K8S_NAMESPACE: {{ .Values.namespace | quote }}
  POLYAXON_K8S_APP_NAME: {{ template "polyaxon.fullname" . }}
  POLYAXON_K8S_API_HOST: {{ template "polyaxon.fullname" . }}-api
  {{- if contains "NodePort" .Values.serviceType }}
  POLYAXON_K8S_API_HTTP_PORT: {{ .Values.api.service.nodePort | quote }}
  POLYAXON_K8S_API_WS_PORT: {{ .Values.streams.service.nodePort | quote }}
  {{- else }}
  POLYAXON_K8S_API_HTTP_PORT: {{ .Values.api.service.externalPort | quote }}
  POLYAXON_K8S_API_WS_PORT: {{ .Values.streams.service.externalPort | quote }}
  {{- end }}
  POLYAXON_K8S_APP_CONFIG_NAME: {{ template "polyaxon.fullname" . }}-config
  POLYAXON_K8S_APP_SECRET_NAME: {{ template "polyaxon.fullname" . }}-secret
  POLYAXON_K8S_RABBITMQ_SECRET_NAME: {{ template "rabbitmq.fullname" . }}
  POLYAXON_K8S_HOST: {{ .Values.k8s.host | quote }}
  {{- if .Values.k8s.ssl_ca_cert }}
  POLYAXON_K8S_SSL_CA_CERT: {{ .Values.k8s.ssl_ca_cert | quote }}
  {{- end }}
  {{- if .Values.logLevel }}
  POLYAXON_LOG_LEVEL: {{ .Values.logLevel | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  POLYAXON_K8S_DB_SECRET_NAME: {{ template "postgresql.fullname" . }}
  {{- else }}
  POLYAXON_K8S_DB_SECRET_NAME: {{ template "polyaxon.fullname" . }}-postgres-secret
  {{- end}}
  {{- if (index .Values "docker-registry").enabled }}
  POLYAXON_K8S_REGISTRY_SECRET_NAME: {{ template "docker-registry.fullname" . }}-secret
  {{- else }}
  POLYAXON_K8S_REGISTRY_SECRET_NAME: {{ template "polyaxon.fullname" . }}-registry-secret
  {{- end}}
  {{- if .Values.ttl.heartbeat }}
  POLYAXON_TTL_HEARTBEAT: {{ .Values.ttl.heartbeat | quote }}
  {{- end }}
  {{- if .Values.ttl.token }}
  POLYAXON_TTL_TOKEN: {{ .Values.ttl.token | quote }}
  {{- end }}
  {{- if .Values.ttl.ephemeralToken }}
  POLYAXON_TTL_EPHEMERAL_TOKEN: {{ .Values.ttl.ephemeralToken | quote }}
  {{- end }}
  {{- if .Values.ttl.watchStatuses }}
  POLYAXON_TTL_WATCH_STATUSES: {{ .Values.ttl.watchStatuses | quote }}
  {{- end }}
  POLYAXON_ENVIRONMENT: {{ default "production" .Values.environment | quote }}
  # Run Env
  {{- if ge (int (include "k8s.minor" .)) 8 }}
  POLYAXON_K8S_GPU_RESOURCE_KEY: "nvidia.com/gpu"
  {{- else }}
  POLYAXON_K8S_GPU_RESOURCE_KEY: "alpha.kubernetes.io/nvidia-gpu"
  {{- end }}
  {{- if .Values.tpuTensorflowVersion }}
  POLYAXON_K8S_TPU_TF_VERSION: {{ .Values.tpuTensorflowVersion | quote }}
  {{- end }}
  {{- if .Values.tpuResourceKey }}
  POLYAXON_K8S_TPU_RESOURCE_KEY: {{ .Values.tpuResourceKey | quote }}
  {{- end }}
  # Secrets and ConfigMaps
  POLYAXON_REFS_SECRETS: {{ toJson .Values.secretRefs | quote }}
  POLYAXON_REFS_CONFIG_MAPS: {{ toJson .Values.configmapRefs | quote }}
  # Dirs
  POLYAXON_DIRS_NVIDIA: {{ toJson .Values.dirs.nvidia | quote }}
  {{- if and .Values.mountPaths.nvidia.lib .Values.mountPaths.nvidia.bin .Values.mountPaths.nvidia.libcuda }}
  POLYAXON_MOUNT_PATHS_NVIDIA: {{ toJson .Values.mountPaths.nvidia | quote }}
  LD_LIBRARY_PATH: "{{ .Values.mountPaths.nvidia.lib }}:{{ .Values.mountPaths.nvidia.libcuda }}"
  {{- else if and .Values.dirs.nvidia.lib .Values.dirs.nvidia.bin .Values.dirs.nvidia.libcuda }}
  POLYAXON_MOUNT_PATHS_NVIDIA: {{ toJson .Values.dirs.nvidia | quote }}
  LD_LIBRARY_PATH: "{{ .Values.dirs.nvidia.lib }}:{{ .Values.dirs.nvidia.libcuda }}"
  {{- end }}
  # Admin
  POLYAXON_ADMIN_NAME: {{ .Values.user.username | quote }}
  POLYAXON_ADMIN_MAIL: {{ .Values.user.email | quote }}
  POLYAXON_PASSWORD_LENGTH: {{ default "6" .Values.passwordLength | quote }}
  POLYAXON_ADMIN_VIEW_ENABLED: {{ default "false" .Values.adminViewEnabled | quote }}
  {{- if .Values.adminModels }}
  POLYAXON_ADMIN_MODELS: {{ toJson .Values.adminModels | quote }}
  {{- end }}
  # Email
  {{- if .Values.email.from }}
  POLYAXON_EMAIL_FROM: {{ .Values.email.from | quote }}
  {{- end }}
  {{- if .Values.email.subjectPrefix }}
  POLYAXON_EMAIL_SUBJECT_PREFIX: {{ .Values.email.subjectPrefix | quote }}
  {{- end }}
  POLYAXON_EMAIL_HOST: {{ .Values.email.host | quote }}
  POLYAXON_EMAIL_PORT: {{ .Values.email.port | quote }}
  POLYAXON_EMAIL_USE_TLS: {{ .Values.email.useTls | quote }}
  {{- if .Values.email.hostUser }}
  POLYAXON_EMAIL_HOST_USER: {{ .Values.email.hostUser | quote }}
  {{- end }}
  {{- if .Values.email.backend }}
  POLYAXON_EMAIL_BACKEND: {{ .Values.email.backend | quote }}
  {{- end }}
  # SSL
  {{- if and .Values.ssl.enabled .Values.ssl.secretName }}
  POLYAXON_SSL_ENABLED: "true"
  {{- if and .Values.ssl.path }}
  POLYAXON_SSL_PATH:  {{ .Values.ssl.path | quote }}
  {{- end }}
  {{- end }}
  # Queues
  POLYAXON_QUEUES_REPOS: {{ .Values.queues.repos | quote }}
  POLYAXON_QUEUES_SCHEDULER_HEALTH: {{ .Values.queues.schedulerHealth | quote }}
  POLYAXON_QUEUES_SCHEDULER_EXPERIMENTS: {{ .Values.queues.schedulerExperiments | quote }}
  POLYAXON_QUEUES_SCHEDULER_EXPERIMENT_GROUPS: {{ .Values.queues.schedulerExperimentGroups | quote }}
  POLYAXON_QUEUES_SCHEDULER_PROJECTS: {{ .Values.queues.schedulerProjects | quote }}
  POLYAXON_QUEUES_SCHEDULER_BUILD_JOBS: {{ .Values.queues.schedulerBuildJobs | quote }}
  POLYAXON_QUEUES_SCHEDULER_JOBS: {{ .Values.queues.schedulerJobs | quote }}
  POLYAXON_QUEUES_SCHEDULER_STORES: {{ .Values.queues.schedulerStores | quote }}
  POLYAXON_QUEUES_SCHEDULER_CLEAN: {{ .Values.queues.schedulerClean | quote }}
  POLYAXON_QUEUES_PIPELINES_HEALTH: {{ .Values.queues.pipelinesHealth | quote }}
  POLYAXON_QUEUES_PIPELINES: {{ .Values.queues.pipelines | quote }}
  POLYAXON_QUEUES_CRONS_HEALTH: {{ .Values.queues.cronsHealth | quote }}
  POLYAXON_QUEUES_CRONS_HEARTBEAT: {{ .Values.queues.cronsHeartbeat | quote }}
  POLYAXON_QUEUES_CRONS_EXPERIMENTS: {{ .Values.queues.cronsExperiments | quote }}
  POLYAXON_QUEUES_CRONS_PIPELINES: {{ .Values.queues.cronsPipelines | quote }}
  POLYAXON_QUEUES_CRONS_CLUSTERS: {{ .Values.queues.cronsClusters | quote }}
  POLYAXON_QUEUES_CRONS_CLEAN: {{ .Values.queues.cronsClean | quote }}
  POLYAXON_QUEUES_HP_HEALTH: {{ .Values.queues.hpHealth | quote }}
  POLYAXON_QUEUES_HP: {{ .Values.queues.hp | quote }}
  POLYAXON_QUEUES_EVENTS_HEALTH: {{ .Values.queues.eventsHealth | quote }}
  POLYAXON_QUEUES_EVENTS_NOTIFY: {{ .Values.queues.eventsNotify | quote }}
  POLYAXON_QUEUES_EVENTS_LOG: {{ .Values.queues.eventsLog | quote }}
  POLYAXON_QUEUES_EVENTS_TRACK: {{ .Values.queues.eventsTrack | quote }}
  POLYAXON_QUEUES_K8S_EVENTS_HEALTH: {{ .Values.queues.k8sEventsHealth | quote }}
  POLYAXON_QUEUES_K8S_EVENTS_NAMESPACE: {{ .Values.queues.k8sEventsNamespace | quote }}
  POLYAXON_QUEUES_K8S_EVENTS_RESOURCES: {{ .Values.queues.k8sEventsResources | quote }}
  POLYAXON_QUEUES_K8S_EVENTS_JOB_STATUSES: {{ .Values.queues.k8sEventsJobStatuses | quote }}
  POLYAXON_QUEUES_LOGS_HEALTH: {{ .Values.queues.logsHealth | quote }}
  POLYAXON_QUEUES_LOGS_SIDECARS: {{ .Values.queues.logsSidecars | quote }}
  POLYAXON_QUEUES_LOGS_HANDLERS: {{ .Values.queues.logsHandler | quote }}
  POLYAXON_QUEUES_STREAM_LOGS_SIDECARS: {{ .Values.queues.streamLogsSidecars | quote }}
  POLYAXON_INTERVALS_EXPERIMENTS_SCHEDULER: {{ .Values.intervals.experimentsScheduler | quote }}
  POLYAXON_INTERVALS_EXPERIMENTS_SYNC: {{ .Values.intervals.experimentsSync | quote }}
  POLYAXON_INTERVALS_CLUSTERS_UPDATE_SYSTEM_INFO: {{ .Values.intervals.clustersUpdateSystemInfo | quote }}
  POLYAXON_INTERVALS_CLUSTERS_UPDATE_SYSTEM_NODES: {{ .Values.intervals.clustersUpdateSystemNodes | quote }}
  POLYAXON_INTERVALS_PIPELINES_SCHEDULER: {{ .Values.intervals.pipelinesScheduler | quote }}
  POLYAXON_INTERVALS_OPERATIONS_DEFAULT_RETRY_DELAY: {{ .Values.intervals.operationsDefaultRetryDelay | quote }}
  POLYAXON_INTERVALS_OPERATIONS_MAX_RETRY_DELAY: {{ .Values.intervals.operationsMaxRetryDelay | quote }}
  POLYAXON_CLEANING_INTERVALS_ARCHIVED: {{ .Values.cleaningIntervals.archived | quote }}
  POLYAXON_CELERY_ALWAYS_EAGER: {{ default "false" .Values.celeryEagerMode | quote }}
  POLYAXON_CELERYD_PREFETCH_MULTIPLIER: {{ default "4" .Values.celeryPrefetchMultiplier | quote }}
  # DB
  POLYAXON_DB_USER: {{ default "polyaxon" .Values.postgresql.postgresUser | quote }}
  POLYAXON_DB_NAME: {{ default "polyaxon" .Values.postgresql.postgresDatabase | quote }}
  POLYAXON_DB_PORT: "5432"
  POLYAXON_DB_CONN_MAX_AGE: {{ default "60" .Values.postgresql.connMaxAge | quote }}
  {{- if .Values.postgresql.enabled }}
  POLYAXON_DB_HOST: {{  template "postgresql.fullname" . }}
  {{- else }}
  POLYAXON_DB_HOST: {{ .Values.postgresql.externalPostgresHost | quote }}
  {{- end }}
  # AMQP
  POLYAXON_AMQP_URL: {{ template "rabbitmq.fullname" . }}:5672
  POLYAXON_RABBITMQ_USER: {{ default "" .Values.rabbitmq.rabbitmqUsername | quote }}
  # REDIS
  POLYAXON_REDIS_CELERY_RESULT_BACKEND_URL: redis://{{ template "redis.fullname" . }}:6379/0
  POLYAXON_REDIS_JOB_CONTAINERS_URL: redis://{{ template "redis.fullname" . }}:6379/3
  POLYAXON_REDIS_TO_STREAM_URL: redis://{{ template "redis.fullname" . }}:6379/4
  POLYAXON_REDIS_SESSIONS_URL: redis://{{ template "redis.fullname" . }}:6379/5
  POLYAXON_REDIS_EPHEMERAL_TOKENS_URL: redis://{{ template "redis.fullname" . }}:6379/6
  POLYAXON_REDIS_TTL_URL: redis://{{ template "redis.fullname" . }}:6379/7
  POLYAXON_HEARTBEAT_URL: redis://{{ template "redis.fullname" . }}:6379/8
  POLYAXON_GROUP_CHECKS_URL: redis://{{ template "redis.fullname" . }}:6379/9
  POLYAXON_REDIS_HOST: {{ template "redis.fullname" . }}
  POLYAXON_REDIS_PORT: "6379"
  # Spawner
  POLYAXON_JOB_SIDECAR_LOG_SLEEP_INTERVAL: "1"
  POLYAXON_PUBLIC_PLUGIN_JOBS: {{ default false .Values.publicJobs | quote }}
  POLYAXON_K8S_INGRESS_ENABLED: {{ .Values.ingress.enabled | quote }}
  POLYAXON_K8S_INGRESS_ANNOTATIONS: {{ toJson .Values.ingress.annotations | quote }}
  POLYAXON_K8S_RBAC_ENABLED: {{ .Values.rbac.enabled | quote }}
  POLYAXON_K8S_SERVICE_ACCOUNT_NAME: {{ template "polyaxon.fullname" . }}-serviceaccount
  POLYAXON_K8S_SERVICE_ACCOUNT_EXPERIMENTS: {{ template "polyaxon.fullname" . }}-workers-serviceaccount
  POLYAXON_K8S_SERVICE_ACCOUNT_JOBS: {{ template "polyaxon.fullname" . }}-workers-serviceaccount
  POLYAXON_K8S_SERVICE_ACCOUNT_BUILDS: {{ template "polyaxon.fullname" . }}-workers-serviceaccount
  POLYAXON_JOB_SIDECAR_DOCKER_IMAGE: "{{ .Values.sidecar.image }}:{{ .Values.sidecar.imageTag }}"
  POLYAXON_JOB_SIDECAR_DOCKER_IMAGE_PULL_POLICY: "{{ .Values.sidecar.imagePullPolicy }}"
  POLYAXON_JOB_INIT_DOCKER_IMAGE: "{{ .Values.init.image }}:{{ .Values.init.imageTag }}"
  POLYAXON_JOB_INIT_DOCKER_IMAGE_PULL_POLICY: "{{ .Values.init.imagePullPolicy }}"
  {{- if .Values.buildBackend }}
  POLYAXON_BUILD_BACKEND: {{ .Values.buildBackend | quote }}
  {{- end }}
  POLYAXON_JOB_DOCKERIZER_IMAGE: "{{ .Values.dockerizer.image }}:{{ .Values.dockerizer.imageTag }}"
  POLYAXON_JOB_DOCKERIZER_IMAGE_PULL_POLICY: {{ .Values.dockerizer.imagePullPolicy | quote }}
  POLYAXON_JOB_KANIKO_IMAGE: "{{ .Values.kaniko.image }}:{{ .Values.kaniko.imageTag }}"
  POLYAXON_JOB_KANIKO_IMAGE_PULL_POLICY: {{ .Values.kaniko.imagePullPolicy | quote }}
  POLYAXON_NODE_SELECTOR_CORE: {{ toJson .Values.nodeSelectors.core | quote }}
  POLYAXON_NODE_SELECTOR_EXPERIMENTS: {{ toJson .Values.nodeSelectors.experiments | quote }}
  POLYAXON_NODE_SELECTOR_JOBS: {{ toJson .Values.nodeSelectors.jobs | quote }}
  POLYAXON_NODE_SELECTOR_BUILDS: {{ toJson .Values.nodeSelectors.builds | quote }}
  POLYAXON_NODE_SELECTOR_TENSORBOARDS: {{ toJson .Values.nodeSelectors.tensorboards | quote }}
  POLYAXON_AFFINITY_CORE: {{ toJson .Values.affinity.core | quote }}
  POLYAXON_AFFINITY_EXPERIMENTS: {{ toJson .Values.affinity.experiments | quote }}
  POLYAXON_AFFINITY_JOBS: {{ toJson .Values.affinity.jobs | quote }}
  POLYAXON_AFFINITY_BUILDS: {{ toJson .Values.affinity.builds | quote }}
  POLYAXON_AFFINITY_TENSORBOARDS: {{ toJson .Values.affinity.tensorboards | quote }}
  POLYAXON_TOLERATIONS_CORE: {{ toJson .Values.tolerations.core | quote }}
  POLYAXON_TOLERATIONS_EXPERIMENTS: {{ toJson .Values.tolerations.experiments | quote }}
  POLYAXON_TOLERATIONS_JOBS: {{ toJson .Values.tolerations.jobs | quote }}
  POLYAXON_TOLERATIONS_BUILDS: {{ toJson .Values.tolerations.builds | quote }}
  POLYAXON_TOLERATIONS_TENSORBOARDS: {{ toJson .Values.tolerations.tensorboards | quote }}
  POLYAXON_ROLE_LABELS_API: {{ .Values.roles.api | quote }}
  POLYAXON_ROLE_LABELS_LOG: {{ .Values.roles.log | quote }}
  POLYAXON_ROLE_LABELS_CONFIG: {{ .Values.roles.config | quote }}
  POLYAXON_ROLE_LABELS_HOOKS: {{ .Values.roles.hooks | quote }}
  POLYAXON_ROLE_LABELS_WORKER: {{ .Values.roles.worker | quote }}
  POLYAXON_ROLE_LABELS_DASHBOARD: {{ .Values.roles.dashboard | quote }}
  POLYAXON_TYPE_LABELS_CORE: {{ .Values.types.core | quote }}
  POLYAXON_TYPE_LABELS_RUNNER: {{ .Values.types.runner | quote }}
  POLYAXON_TRACKER_BACKEND: {{ default "publisher" .Values.trackerBackend | quote }}
  POLYAXON_BUILD_ALWAYS_PULL_LATEST: {{ default "false" .Values.build_always_pull_latest | quote }}
  # Default images for tensorboards
  {{- if .Values.tensorboardDockerImage }}
  POLYAXON_TENSORBOARD_DOCKER_IMAGE: {{ .Values.tensorboardDockerImage | quote }}
  {{- end }}
  # Default images for notebooks
  {{- if .Values.notebookDockerImage }}
  POLYAXON_NOTEBOOK_DOCKER_IMAGE: {{ .Values.notebookDockerImage | quote }}
  {{- end }}
  # Default notebook for notebooks
  {{- if .Values.notebookBackend }}
  POLYAXON_NOTEBOOK_BACKEND: {{ .Values.notebookBackend | quote }}
  {{- end }}
  {{- if .Values.mountCodeInNotebooks }}
  POLYAXON_MOUNT_CODE_IN_NOTEBOOKS: {{ .Values.mountCodeInNotebooks | quote }}
  {{- end }}
  # Registry
  {{- if (index .Values "docker-registry").enabled }}
  POLYAXON_REGISTRY_IN_CLUSTER: "true"
  POLYAXON_REGISTRY_HOST: {{ template "docker-registry.fullname" . }}
  POLYAXON_REGISTRY_PORT: {{ (index .Values "docker-registry").service.port | quote }}
  POLYAXON_REGISTRY_NODE_PORT: {{ (index .Values "docker-registry").service.nodePort | quote }}
  {{- else }}
  POLYAXON_REGISTRY_IN_CLUSTER: "false"
  POLYAXON_REGISTRY_HOST: {{ (index .Values "docker-registry").external.host }}
  POLYAXON_REGISTRY_PORT: {{ (index .Values "docker-registry").external.port | quote }} 
  {{- end }}
  # Versions
  POLYAXON_CLI_MIN_VERSION: "0.4.2"
  POLYAXON_CLI_LATEST_VERSION: "0.4.2"
  POLYAXON_PLATFORM_MIN_VERSION: "0.4.2"
  POLYAXON_PLATFORM_LATEST_VERSION: "0.4.2"
  POLYAXON_LIB_MIN_VERSION: "0.0.2"
  POLYAXON_LIB_LATEST_VERSION: "0.0.5"
  POLYAXON_CHART_VERSION: {{ .Chart.Version | quote }}
  POLYAXON_CHART_IS_UPGRADE: {{ .Release.IsUpgrade | quote }}
  POLYAXON_CHART_REVISION: {{ .Release.Revision | quote }}
  # Integrations
  {{- if .Values.integrations.slack }}
  POLYAXON_INTEGRATIONS_SLACK_WEBHOOKS: {{ toJson .Values.integrations.slack | quote }}
  {{- end }}
  {{- if .Values.integrations.hipchat }}
  POLYAXON_INTEGRATIONS_HIPCHAT_WEBHOOKS: {{ toJson .Values.integrations.hipchat | quote }}
  {{- end }}
  {{- if .Values.integrations.mattermost }}
  POLYAXON_INTEGRATIONS_HIPCHAT_WEBHOOKS: {{ toJson .Values.integrations.mattermost | quote }}
  {{- end }}
  {{- if .Values.integrations.discord }}
  POLYAXON_INTEGRATIONS_DISCORD_WEBHOOKS: {{ toJson .Values.integrations.discord | quote }}
  {{- end }}
  {{- if .Values.integrations.pagerduty }}
  POLYAXON_INTEGRATIONS_PAGER_DUTY_WEBHOOKS: {{ toJson .Values.integrations.pagerduty | quote }}
  {{- end }}
  {{- if .Values.integrations.webhooks }}
  POLYAXON_INTEGRATIONS_WEBHOOKS: {{ toJson .Values.integrations.webhooks | quote }}
  {{- end }}
  # Auth
  {{- if .Values.auth.ldap.enabled }}
  POLYAXON_AUTH_LDAP: "true"
  POLYAXON_AUTH_LDAP_SERVER_URI: {{ .Values.auth.ldap.serverUri | quote }}
  POLYAXON_AUTH_LDAP_GLOBAL_OPTIONS: {{ toJson .Values.auth.ldap.globalOptions | quote }}
  POLYAXON_AUTH_LDAP_CONNECTION_OPTIONS: {{ toJson .Values.auth.ldap.connectionOptions | quote }}
  POLYAXON_AUTH_LDAP_BIND_DN: {{ .Values.auth.ldap.bindDN | quote }}
  POLYAXON_AUTH_LDAP_USER_SEARCH_BASE_DN: {{ .Values.auth.ldap.userSearchBaseDN | quote }}
  POLYAXON_AUTH_LDAP_USER_SEARCH_FILTERSTR: {{ .Values.auth.ldap.userSearchFilterStr | quote }}
  POLYAXON_AUTH_LDAP_USER_DN_TEMPLATE: {{ .Values.auth.ldap.userDNTemplate | quote }}
  POLYAXON_AUTH_LDAP_START_TLS: {{ .Values.auth.ldap.startTLS | quote }}
  POLYAXON_AUTH_LDAP_USER_ATTR_MAP: {{ toJson .Values.auth.ldap.userAttrMap | quote }}
  POLYAXON_AUTH_LDAP_GROUP_SEARCH_BASE_DN: {{ .Values.auth.ldap.groupSearchBaseDN | quote }}
  POLYAXON_AUTH_LDAP_GROUP_SEARCH_GROUP_TYPE: {{ .Values.auth.ldap.groupSearchGroupType | quote }}
  {{- if .Values.auth.ldap.requireGroup }}
  POLYAXON_AUTH_LDAP_REQUIRE_GROUP: {{ .Values.auth.ldap.requireGroup | quote }}
  {{- end }}
  {{- if .Values.auth.ldap.denyGroup }}
  POLYAXON_AUTH_LDAP_DENY_GROUP: {{ .Values.auth.ldap.denyGroup | quote }}
  {{- end }}
  {{- end }}
  POLYAXON_AUTH_GITHUB: {{ .Values.auth.github.enabled | quote }}
  POLYAXON_AUTH_BITBUCKET: {{ .Values.auth.bitbucket.enabled | quote }}
  POLYAXON_AUTH_AZURE: {{ .Values.auth.azure.enabled | quote }}
  POLYAXON_AUTH_GITLAB: {{ .Values.auth.gitlab.enabled | quote }}
  {{- if .Values.auth.gitlab.enabled }}
  POLYAXON_AUTH_GITLAB_URL: {{ .Values.auth.gitlab.url | quote }}
  {{- end }}
