{{- if .Values.compiler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-compiler
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.platform" . | indent 4 }}
{{ include "config.compiler.annotations" . | indent 4 }}
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-compiler
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreWorker" . | indent 4 }}
{{ include "config.compiler.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.compiler.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-compiler
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{ include "config.checksum.platform" . | indent 8 }}
{{ include "config.compiler.annotations" . | indent 8 }}
      labels:
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-compiler
{{ include "config.labels.common" . | indent 8 }}
{{ include "config.labels.roles.coreWorker" . | indent 8 }}
{{ include "config.compiler.labels" . | indent 8 }}
    spec:
{{ include "securityContext.pod" . | indent 6 }}
{{ include "config.agent.sa" . | indent 6 }}
{{ include "config.compiler.scheduling" . | indent 6 }}
{{ include "config.compiler.imagePullSecrets" . | indent 6}}
{{ include "config.compiler.priorityClassName" . | indent 6}}
      containers:
      - name: {{ .Chart.Name }}-compiler
        image: "{{ .Values.compiler.image }}:{{ .Values.compiler.imageTag }}"
        imagePullPolicy: {{ .Values.compiler.imagePullPolicy }}
{{ include "securityContext.container" . | indent 8 }}
        args: ["compiler", "--concurrency={{ .Values.compiler.concurrency }}"]
        envFrom:
{{ include "config.envFrom.common" . | indent 8 }}
{{ include "config.envFrom.secret" . | indent 8 }}
{{ include "config.envFrom.platform" . | indent 8 }}
{{ include "config.envFrom.proxies" . | indent 8 }}
        env:
{{ include "config.envs" . | indent 8 }}
{{ include "config.compiler.celery" . | indent 8 }}
        livenessProbe:
          exec:
            command: ["/bin/bash", "./entrypoint.sh", "healthz"]
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 10
          timeoutSeconds: 10
        readinessProbe:
          exec:
            command: ["/bin/bash", "./entrypoint.sh", "healthz"]
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 10
          timeoutSeconds: 10
        resources:
          requests:
{{ toYaml .Values.compiler.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.compiler.resources.limits | indent 12 }}
          {{- end }}
{{- end }}
