apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-clean-runs"
  labels:
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-clean-runs
{{ include "config.labels.common" . | indent 4 }}
{{ include "config.labels.roles.coreHooks" . | indent 4 }}
{{ include "config.agent.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
{{ include "config.agent.annotations" . | indent 4 }}
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-clean-runs"
      annotations:
{{ include "config.agent.labels" . | indent 8 }}
      labels:
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-clean-runs
{{ include "config.agent.labels" . | indent 8 }}
    spec:
{{ include "securityContext.pod" . | indent 6 }}
{{ include "config.agent.scheduling" . | indent 6 }}
{{ include "config.agent.sa" . | indent 6 }}
{{ include "config.agent.imagePullSecrets" . | indent 6}}
{{ include "config.agent.priorityClassName" . | indent 6}}
      restartPolicy: Never
      activeDeadlineSeconds: 360
      containers:
      - name: clean-runs
        image: "{{ .Values.cleanHooks.image }}:{{ .Values.cleanHooks.imageTag }}"
        imagePullPolicy: {{ .Values.cleanHooks.imagePullPolicy }}
{{ include "securityContext.container" . | indent 8 }}
        command: ["polyaxon"]
        args: ["admin", "clean-ops", "--namespace={{ .Release.Namespace }}", "--in-cluster", "--delete"]
        envFrom:
{{ include "config.envFrom.common" . | indent 8 }}
